#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

# Use the 'ip' command to retrieve IPv4 addresses
ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1
